version: '3'

services:
  nginx:
    image: nginx:1.17.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./certs/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - app
    env_file: .env
    networks:
      - app-network
  app:
    image: crcoerph/edbd:0.2.2
    expose:
      - "8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
